# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e80caf17dce9a41076342aae17ded230f8abef8415f73fe5bb47727a549b975dd70ee546eb3316b4fb4eb168afb157a34c9cd063aff153a4b290bb4feab4614

test:
  secret_key_base: ce7d85404bd004dba896d5eaa8777fd46eeeb39db16a94fec3e9f39302f318b586622e480a0fa7825ad632a964f50e702b63f546e07908f81708a125ba67f66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
